### ISSUE TITLE
Add CI build

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot-avalonia#6]

**Comment by worldbeater** [comment]
Created a CI pipeline on [Azure Pipelines](https://worldbeater.visualstudio.com/OxyPlot.Avalonia/_build?definitionId=2&_a=summary). 
Currently adjusting `azure-pipelines.yml` to have CD working as well for NuGet packages.

**Comment by VisualMelon** [comment]
CI seems to be up-and running; can this be closed?

**Comment by rstm-sf** [comment]
Hello!

Please, could you give access to the master (develop) pre-release assembly via myget.org?

**Comment by worldbeater** [comment]
Well. Discovered that Azure Artifacts actually supports custom NuGet feeds, so starting from this moment the commits to the `master` branch will trigger CI and CD, resulting in a published package to a feed, which can be found [here](https://worldbeater.visualstudio.com/OxyPlot.Avalonia/_packaging?_a=feed&feed=OxyPlot.Avalonia-CI). In order to install the package builds from this feed, use the following `nuget.config` file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="OxyPlot.Avalonia-CI" value="https://worldbeater.pkgs.visualstudio.com/OxyPlot.Avalonia/_packaging/OxyPlot.Avalonia-CI/nuget/v3/index.json" />
  </packageSources>
</configuration>
```
